import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Header from "@/components/Header";
import Aside from "@/components/Aside";
import { Separator } from "@radix-ui/react-separator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <div className="flex flex-col h-screen overflow-hidden">
        {/* <div id="header" className="w-full flex-shrink-0">
          <Header/>
        </div> */}
          <main className="flex h-screen w-full flex-shrink-0">
            <Aside/>

            <Separator orientation="vertical" />
            <div id="content" className="px-10 py-5 max-h-full w-full overflow-y-auto overflow-hidden">
              {children}
            </div>
          </main>
        </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
